export * from "./ERAsegAuthenticator";
export * from "./getDataReg";
export * from "./getERAseg";
export * from "./NuevaEPSAuth";
export * from "./CoosaludESPAuth";
export * from "./birthFormatter";
export * from "./toTitleCase";
export * from "./ageCalculator";
export * from "./copyFunction";